### ISSUE TITLE
Kan de variabele `$genericMsg` of methode `logError` nergens vinden

### ISSUE THREAD

**Issue by JeroenHeemskerk** [Corby7/educom-webshop-oop#24]
In de code hieronder wordt $this->genericMsg gebruikt, 
https://github.com/Corby7/educom-webshop-oop/blob/aa72ecad6e6b92be8b2bb21bf0bdb7b88583ebb4/models/usermodel.php#L164-L171
Maar deze wordt niet gedefinieerd bovenin UserModel, klopt dat?

Ook zie ik in het catch block nog staan `$this->model->genericErr` ik denk dat je deze over het hoofd hebt gezien bij het refactoren

**Comment by JeroenHeemskerk** [comment]
Ook de `logError` functie kan niet worden gevonden

**Comment by Corby7** [comment]
showgenericmsg wordt net als showgenericerr in de basic_doc gedefinieerd. Waar zou de functie logError plaats moeten nemen?
